### ISSUE TITLE
device is write locked

### ISSUE THREAD

**Issue by ioito** [XuCpeng/GIGABYTE-B360M_AORUS_PRO-8700-Hackintosh-OpenCore-EFI#1]
有没有遇见过卡在 device is write locked 进行不下去的情况？

**Comment by XuCpeng** [comment]
我安装和使用的过程没有遇到，推测与磁盘有关。可以尝试一下以下方案：
1. 确认BIOS设置和EFI的efi、kext
2. 确认磁盘分区表为GUID（GPT）
3. 将macOS的安装分区或整个磁盘格式化为FAT32
4. 使用macOS安装U盘中的磁盘工具将FAT32的分区格式化为APFS
5. 重新安装macOS到上述分区

**Comment by ioito** [comment]
再问下，我也是b360，但是开启了Above 4G decoding之后bios进不去了，只能重置，你开启Above 4G decoding后有这个问题没？

**Comment by XuCpeng** [comment]
> 再问下，我也是b360，但是开启了Above 4G decoding之后bios进不去了，只能重置，你开启Above 4G decoding后有这个问题没？

没有遇到过，进不了Bios的情况比较少见 可能是bios本身的缺陷

**Comment by ioito** [comment]
安装好之后卡在 [ PCI configuration begin ]
我用了你的EC依然进不去系统

**Comment by XuCpeng** [comment]
> 安装好之后卡在 [ PCI configuration begin ]
> 我用了你的EC依然进不去系统

EC应该没问题，之前用的是PreBuilt的EC。我刚刚也更新了使用SSDTTime生成的EC，可以试一下。不过我觉得可能不是这个问题，貌似还和内存有关系。

**Comment by ioito** [comment]
现在已经安装好了，2060显卡能驱动么，dp接口你插在主板上还是显卡上

**Comment by XuCpeng** [comment]
> 现在已经安装好了，2060显卡能驱动么，dp接口你插在主板上还是显卡上

macOS 10.13.6 以上版本无法驱动任何英伟达显卡，20系英伟达不能被任何版本macOS驱动。在可预见的将来也不可能。
