### ISSUE TITLE
我要是用免驱的独显和网卡需要修改哪些参数，还是说需要我自己去测试= =

### ISSUE THREAD

**Issue by ysh0566** [XuCpeng/GIGABYTE-B360M_AORUS_PRO-8700-Hackintosh-OpenCore-EFI#2]

**Comment by XuCpeng** [comment]
是的，需要您自己进行测试，因为客观的硬件差异，不会有完全通用的EFI。

- 免驱的独显理论上去掉启动参数中的 -wegnoegpu 即可驱动。但是因为独显型号众多，一次性成功是很幸运的。
- 有线网卡大多数不需要额外修改即可驱动。
- 无线网卡如果不免驱，则需要针对自己的型号去找驱动。

**Comment by ysh0566** [comment]
谢谢老哥，闲的时候测试下，怕炸了
