### ISSUE TITLE
oc引导

### ISSUE THREAD

**Issue by a14738807853** [XuCpeng/GIGABYTE-B360M_AORUS_PRO-8700-Hackintosh-OpenCore-EFI#3]
用3月30号的efi文件进行安装
在oc引导只有3个选项 没有可以安装黑苹果的选项

**Comment by a14738807853** [comment]
修改config文件
Misc，Security，ScanPolicy，设置0
已解决

**Comment by XuCpeng** [comment]
感谢反馈，这里的确疏忽了，已经将ScanPolicy由默认值改为了0。
